with open('pyproject.toml', 'w', encoding='utf-8') as f:
    f.write('[build-system]\n')
    f.write('requires = ["setuptools>=45", "wheel"]\n')
    f.write('build-backend = "setuptools.build_meta"\n')
    f.write('\n')
    f.write('[project]\n')
    f.write('name = "email-triage-env"\n')
    f.write('version = "1.0.0"\n')
    f.write('description = "Email Triage RL Environment"\n')
    f.write('requires-python = ">=3.10"\n')
    f.write('dependencies = [\n')
    f.write('    "openenv-core>=0.2.0",\n')
    f.write('    "fastapi>=0.104.0",\n')
    f.write('    "uvicorn>=0.24.0",\n')
    f.write('    "pydantic>=2.0.0",\n')
    f.write('    "requests>=2.25.0",\n')
    f.write(']\n')
    f.write('\n')
    f.write('[project.scripts]\n')
    f.write('server = "server.app:app"\n')
print('Done')
